### ISSUE TITLE
component build doesn't seems to respect local world prefix

### ISSUE THREAD

**Issue by sehz** [bytecodealliance/cargo-component#144]
I have a WIT definition with something like this
```
package infinyon:operator

interface operator-graph {
......
}

world operator-component {
  import operator-graph
  export run: func()
}
```

However, when I run the build (non-reactive), it always generates a component with `root` prefix instead of 'infinyon`

```
package root:component

world root {
  import infinyon:operator/operator-graph

  export run: func()
}
```

Is there anyway to change this behavior? or am I misunderstanding behavior of world?

**Comment by esoterra** [comment]
What does your Cargo.toml look like?

**Comment by sehz** [comment]
```
[package]
name = "operator-guest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:my-component"


[package.metadata.component.dependencies]


[dependencies]
cargo-component-bindings = { git = "https://github.com/bytecodealliance/cargo-component" }
```

**Comment by esoterra** [comment]
I would bet that whatever tool you're using to generate the WIT that corresponds to your components type is choosing the `root:component` package name for it arbitrarily.

Components don't intrinsically know their own name or the name of the world they were built against because the name of a component depends on how/where it's published and a given component is compatible with any world matching its type not just the one it was built against. What they do record internally is the identity of the interfaces they import and export, which is why the interfaces in the generated WIT do track your original identifiers.

**Comment by sehz** [comment]
I am just running `cargo component build`.

**Comment by peterhuene** [comment]
> I would bet that whatever tool you're using to generate the WIT that corresponds to your components type is choosing the root:component package name for it arbitrarily.

That's correct. `wit-component` [chooses an arbitrary name](https://github.com/bytecodealliance/wasm-tools/blob/585a0bdd8f49fc05d076effaa96e63d97f420578/crates/wit-component/src/decoding.rs#L167-L174) for the package when decoding a component because the original package name is not encoded in the wasm.

I think we should probably be encoding the package name in the file header of the wasm (as opposed to, say, the `names` custom section), as technically the `package` directive in WIT has semantic meaning.

We should probably file an issue with the component model proposal.

**Comment by esoterra** [comment]
Not including the components own identity in the Wasm is, from the view of the registry security design, intentional and a feature. A given component binary can't be trusted to assert its own identity without context/verification and many kinds of vulnerabilities can arise from trusting them to do so.

**Comment by sehz** [comment]
The explanation makes sense.  Closing this
