### ISSUE TITLE
`cargo_component_bindings::generate!()` requires component implementation in the same mod

### ISSUE THREAD

**Issue by sehz** [bytecodealliance/cargo-component#149]
Everything works as long as interface implementation and component implementation are in the same mod
```
cargo_component_bindings::generate!();

use bindings::exports::my_world::run;

struct Component{};

impl run for Component {
   .....
}
```

But trying to move component implementation into separate mod  result in message: `no Component in generate` as in this structure:

```

cargo_component_bindings::generate!();

mod component {
  
  use super::bindings::exports::my_world::run;
  
  struct Component{};
  
  impl run for Component {
    .....
  }
}

```

**Comment by peterhuene** [comment]
Hi @sehz, thanks for opening this issue.

By default, the `generate!` macro assumes that the implementation is at `super::Component` (from the bindings module).

However, one may override this by using the `implementor` parameter to the macro:

Give the following a try (however, `Component` will probably need to be `pub`):
```rust
cargo_component_bindings::generate!({
    implementor: crate::component::Component
});
```

Let me know if that doesn't work, otherwise it's a bug.

**Comment by sehz** [comment]
that works! Thanks.  closing this
