### ISSUE TITLE
Imported component dependency has wrong type on execution

### ISSUE THREAD

**Issue by Falumpaset** [bytecodealliance/cargo-component#155]
Hello! I am a big fan of the project. However, I ran into some problems. 

I tried to build a sample application with the cargo component. For that, I created a reactor component.

I imported wasi:http to send a request to a server for that component. 

`Cargo.toml`

```
[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "falumpaset:reactor"
adapter = "../../adapter/wasi_snapshot_preview1.reactor.wasm"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
"wasi:http" = { path = "../wasi-http/wit" }
"wasi:io" = { path = "../wasi-http/wit/deps/io/"}
```

`wit/world.wit`
```
package falumpaset:http

interface backend {
    fetch: func(url: string) -> string
}

/// An example world for the component to target.
world reactor {
    import wasi:http/incoming-handler
    import wasi:http/outgoing-handler
    export backend
}

```

I want to call that reactor from a command component. I got from #120 that I can depend on the reactor.wasm by declaring it as a component dependency.

For the command component:

`Cargo.toml`

```
[package.metadata.component]
package = "falumpaset:application"
adapter = "../../adapter/wasi_snapshot_preview1.command.wasm"

[package.metadata.component.dependencies]
"falumpaset:http" = { path = "../wasi-http-reactor/target/wasm32-wasi/release/wasi_http_reactor.wasm" }

[package.metadata.component.target]
path = "wit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-component-bindings = { git = "https://github.com/bytecodealliance/cargo-component"}

```

`src/main.rs`
```
cargo_component_bindings::generate!();
use crate::bindings::falumpaset::http::backend::fetch;

fn main() {
    let response = fetch("localhost:8080");
    println!("{}", response);
}
```

After compilation, I get the following components:

```(component
  (type (;0;)
    (instance
      (type (;0;) (func (param "url" string) (result string)))
      (export (;0;) "fetch" (func (type 0)))
    )
  )
  (import (interface "falumpaset:http/backend") (instance (;0;) (type 0)))
  (type (;1;)
    (instance

[...]
```
However, when executing the component with wasmtime, I get the following error message:
```failed to run main module 

Caused by:
    0: import `falumpaset:http/backend` has the wrong type
    1: instance export `fetch` has the wrong type
    2: expected func found nothing
```
    
What I tried to resolve the issue: I wrote a world for the command component, imported the reactor into it and declared the reactor .wasm file as a target dependency. That didn't resolve it either.

I'd be super happy if you could help me!

**Comment by peterhuene** [comment]
Hi @Falumpaset.

The error message is indicating that Wasmtime doesn't know how to resolve the `falumpaset:http/backend` instance import (the host didn't provide the interface).

When you build a component that depends on another component using `cargo-component`, the resulting component imports the dependency via an _instance_, meaning the component is effectively delegating the instantiation of the dependency to someone else.

One way to solve the problem would be to have a custom host that loads and instantiates the dependency so that the other component can receive it as an import.

The more common way to solve the problem is to create a _composed_ component that wires up the instantiation of the dependency internally, effectively erasing the dependency so that the host (Wasmtime) doesn't know about i.

There are two composing tools out there at the moment: [wasm-compose](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-compose) and [wasmbuilder.app](https://wasmbuilder.app).

Note that currently neither tool supports the latest HEAD of WASI because WASI recently updated to resources and resources aren't yet supported in the composing tools. But if you're using Wasmtime 13 and the built-in WASI adapter for `cargo-component`, it should work.

Hopefully we'll have the composing tools updated to support the latest WASI soon.

**Comment by Falumpaset** [comment]
Hey @peterhuene, thank you very much for coming back to me!

So, do I understand correctly that when I import wasi components like wasi-http, the wasmtime runtime instantiates the module for me?

**Comment by Falumpaset** [comment]
Hey @peterhuene, thank you very much for coming back to me!

So, do I understand correctly that when I execute my components with `wasmtime -W component-model -S common  -S http --wasm component-model PATH,` wasmtime instantiates the host implementations for http and common as modules to resolve the imports?

That's interesting to know! However, doing that for every custom component would be a bit complicated.

When browsing the component model specification, I found this:

```
(component
  (core module $A
    (func (export "one") (result i32) (i32.const 1))
  )
  (core module $B
    (func (import "a" "one") (result i32))
  )
  (core instance $a (instantiate $A))
  (core instance $b (instantiate $B (with "a" (instance $a))))
)
```
Is it correct to assume that the tools you mentioned inject such instantiation logic into the component? Assuming that wasmtime instantiates the wasi modules for the component to resolve the import. Could I compose the wasi modules into my application and gain independence from runtime implementations?

Also, I'd like to ask you for some guidance. The sample I provided defines the component as a composure of modules. The component handles the control flow by instantiating and injecting modules depending on which flow I want to take through the component. I need to figure out where to build modules and where to make components. 

Assuming I build an application, is the application one single component with multiple modules or composure of components? If the latter is the case, how is the component instantiation handled?

I will go ahead and solve my problem with the wasmbuilder. I use wasmtime 14, so fingers crossed!

Finally, I've written down all the knowledge and steps I needed to build a WebAssembly application. As you've stated in the mission statement for the cargo component, that knowledge takes time to come by. Would you happen to know a place where I can put it so that others have a better time adopting WebAssembly?

**Comment by peterhuene** [comment]
> So, do I understand correctly that when I execute my components with wasmtime -W component-model -S common  -S http --wasm component-model PATH, wasmtime instantiates the host implementations for http and common as modules to resolve the imports?

That's correct, but the WASI implementation that Wasmtime provides isn't implemented in WebAssembly, but in native Rust code.

> Is it correct to assume that the tools you mentioned inject such instantiation logic into the component? 

That's exactly what tools like `wasm-compose` do, they either import or define (i.e. embed) other component dependencies and then use the instantiation instructions to inform the runtime of how dependencies should be created.

> Assuming that wasmtime instantiates the wasi modules for the component to resolve the import. Could I compose the wasi modules into my application and gain independence from runtime implementations?

While Wasmtime doesn't use WebAssembly modules for its WASI implementation, there's actually nothing preventing WASI from being "virtualized" in terms of WebAssembly and thereby removing the WASI imports from the host. In fact, [wasi-virt](https://github.com/bytecodealliance/wasi-virt) is one such tool that can implement WASI in terms of other components which can be linked in with yours to erase the WASI imports.

> Do you think this is the optimal approach? We could call other components more elegantly with the cargo component/ wit bindgen bindings.

The code you linked to is an implementation of a custom host and it is only instantiating a single component, so it expects the component being instantiated to not have any imports on other components that host isn't aware of; thus the example needs a `wasm-compose` step to bundle the two components together so that the custom host can instantiate it as a single unit.

> We could call other components more elegantly with the cargo component/ wit bindgen bindings.

Could you explain more about what you mean? In the host, we use the `wasmtime::component::bindgen!` macro from Wasmtime to automatically generate the traits the host needs to implement to run the component, whereas cargo-component/wit-bindgen are for generating bindings in guest (i.e. WebAssembly component) code.

> Finally, I've written down all the knowledge and steps I needed to build a WebAssembly application. As you've stated in the mission statement for the cargo component, that knowledge takes time to come by. Where can I put it so that others have a better time adopting WebAssembly?

This is an awesome sentiment!  We have some [Component Model documentation](https://component-model.bytecodealliance.org) that's being maintained by the community, so I'm sure any contributions would be very welcome there!

**Comment by Falumpaset** [comment]
Hello @peterhuene, thanks for your input. 

> That's exactly what tools like wasm-compose do, they either import or define (i.e. embed) other component dependencies and then use the instantiation instructions to inform the runtime of how dependencies should be created.

I report that I was able to do that finally. Your update to 0.4.0 and [this](https://github.com/bytecodealliance/wasm-tools/pull/1261) did the magic. I'm excited that I built a multi-component application with wasi:HTTP! Feels like a big step forward.

In case it is relevant for others: 

```
wasm-tools compose -c config.yml -o composed.wasm
```

With the config: 
```
instantiations:
  $input:
    arguments:
      falumpaset:backend/connector@0.1.0:
        instance: backend
dependencies:
  backend: backend.wasm
```

> Could you explain more about what you mean? In the host, we use the wasmtime::component::bindgen! macro from Wasmtime to automatically generate the traits the host needs to implement to run the component, whereas cargo-component/wit-bindgen are for generating bindings in guest (i.e. WebAssembly component) code.

Compiling my whole application to WebAssembly is the way I want to go. So, I'm not using a host implementation per se. I prefer to work with your cargo component toolchain on the guest and execute my application with the cli like so.
`wasmtime -W component-model -S common  -S http --wasm component-model composed.wasm`

Could you elaborate if there's any drawback to this instead of using an application as the host and using the host bindings instead?

**Comment by tysonrm** [comment]
This is a great issue. So I have two related issues/questions: 

1. I'm currently using the wasmtime embedding API to control the loading of components - fetching them from github and creating them from binary. That's the short version. The detail is that first I am using the wac_graph api to compose several components, returning the composite and instantiating that using the cranelift generated wit bindings so i can call the remaining exports in the composite more easily. I'm getting a similar error to the one above. I am using resources but just by virtue of the fact that the error says "expected resource x found nothing" I assume, unlike the other comp tools (at the time), resources are supported by the wac api. In every wac api example i can find, there is an explicit call to set the argument of the dependent interface/function, although scanning the code it appears that matching interfaces are handled implicitly, which if i understand should only require designating one of the components as the primary or the component whose exports will remain vs disappeaeing into the composition. Do I have that right?
