### ISSUE TITLE
Consider using `cargo add` in the `new` command

### ISSUE THREAD

**Issue by tomasol** [bytecodealliance/cargo-component#204]
Currently `cargo component new` [generates](https://github.com/bytecodealliance/cargo-component/blob/205c6ee978d57b450cd1148a481e36c8bbb69c8c/src/commands/new.rs#L292) the dependency with the version fixed in the binary, e.g. `cargo-component-bindings = "0.6.0"` .
I would prefer having the same behavior as when calling `cargo add cargo-component-bindings`, generating `cargo-component-bindings.workspace = true` if I am inside a workspace and have version set in `[workspace.dependencies]`. If the version is not set, `cargo add` checks the latest version which is I believe preferable.

**Comment by peterhuene** [comment]
@tomasol Thanks for the suggestion!

I think spawning cargo to do what you suggest is a good idea so that we don't have to duplicate the logic for detecting workspace membership.

The `new` subcommand of `cargo-component` predates `cargo add` and needs to modify the manifest anyway, so that's primarily why it's done that way now.
