### ISSUE TITLE
wit pubilsh --init fails to register the WIT package to wa.dev, while it successfully create a pacakge on the registry

### ISSUE THREAD

**Issue by chikoski** [bytecodealliance/cargo-component#277]
## Expected behavior

`wit publish --init` should initialize a package and register the WIT file that is already available in the working directory. 

## Actual behavior

I found the following error when I tried to register my WIT package to wa.dev:

```
error: the package was rejected by the registry: chikoski:name package successfully created by the registry, but rejected your init record. The registry signed one for you. OK to publish.
```

After the error message was emitted, I found the package is registered to the wa.dev with no information about the WIT package I tried to register as the following screenshot:

<img width="841" alt="スクリーンショット 2024-04-18 22 07 25" src="https://github.com/bytecodealliance/cargo-component/assets/47718/92647aeb-3650-4b09-ac4d-184e9a2b259b">

I did the `wit publish` again, and this time it successfully register the WIT package build.

## Versions

- wit: 0.10.0
- Registered WIT package: https://wa.dev/chikoski:name
- WIT file for the WIT package: 

```wit
package chikoski:name;

world default{
    export name: func() -> string;
}
```

**Comment by peterhuene** [comment]
@macovedj is this related to your current PR?

**Comment by calvinrp** [comment]
@peterhuene This is unrelated.

@chikoski This is definitely confusing. At a recent Registry SIG meeting, we discussed a fix for the error message presentation. We should also explain the `init` command more. A little context...

Both `wit publish --init` and `warg publish init` operate in the same way. They create a new package with an `Init` record but do not publish any releases. It requires a follow on `wit publish` or `warg publish release` to actually publish a release.

In the Warg protocol, an `Init` [entry](https://github.com/bytecodealliance/registry/blob/main/crates/protocol/src/package/model.rs#L74-L79) just puts the signing key that is valid for future publishes.

But since user key management is often painful and tricky, on `wa.dev` registry service, we opted to handle the key management on behalf of the user. The easiest way to do that for package logs is to put a registry operator key in each package `Init` record instead of one of the user's keys. That way, the registry can handle the key management for the package.

We also wanted to give users the ability to create new packages from the CLI without requiring the UI. So when you do `warg publish init`, it does work but technically is an error. An error because we reject the `Init` record that the user's CLI signed and use one created by the registry service instead.

The Registry SIG meeting discussion concluded that we should have a better presentation for these types of errors. But it should still be an error since it is a rejection.

Let me know if that makes sense and if you think better messaging would be an OK solution.

**Comment by chikoski** [comment]
Thanks for the explanation. I understand that is an intended  behavior.

I expected `warg publish` and `wit publish` work as `cargo` or `npm`. These two commands enables us to publish the libraries with single step.  Perhaps, I should submit a feature request as another issue, such that a command to create `Init` record and submit the package to the created record as we can do with the two commands.

Let me close this issue for now.
