### ISSUE TITLE
Document system dependencies needed for installation

### ISSUE THREAD

**Issue by rylev** [bytecodealliance/cargo-component#54]
I ran into an issue when installing that I didn't have protobuf installed on my machine. It would be nice if system dependencies were documented in the README.

I imagine in addition to protobut that a clang/gcc might be necessary (due to the use of the cc crate which might be compiling some c dependencies?). Are there any others? libssl? Happy to send a PR adding this documentation to the README!

**Comment by peterhuene** [comment]
We document this [here](https://github.com/bytecodealliance/cargo-component#prerequisites) but the README is a bit long.

The dependency on protobuf comes from `warg`, which uses it for the format of a component package log.

We should probably rearrange the README so that the installation instructions are surfaced closer to the top, though.
