### ISSUE TITLE
cargo install fails

### ISSUE THREAD

**Issue by schorg** [bytecodealliance/cargo-component#77]
Wanted to try some component examples, to demonstrate Wasm components,  but

`cargo install --git https://github.com/bytecodealliance/cargo-component`

fails with the following error:

```
error[E0432]: unresolved import `warg_client::storage::PackageStorage`
  --> src/registry.rs:24:44
   |
24 |     storage::{ContentStorage, PackageInfo, PackageStorage},
   |                                            ^^^^^^^^^^^^^^ no `PackageStorage` in `storage`

error[E0599]: no method named `packages` found for reference `&warg_client::Client<FileSystemPackageStorage, FileSystemContentStorage>` in the current scope
   --> src/registry.rs:740:30
    |
740 |                 match client.packages().load_package(id.as_str()).await? {
    |                              ^^^^^^^^ method not found in `&Client<FileSystemPackageStorage, FileSystemContentStorage>`
```

It worked 1 week ago. Do I need to wait until it get's more stable?

**Comment by schorg** [comment]
Compiled it and installed it locally with revision `[eee527f](https://github.com/bytecodealliance/registry/commit/eee527f91d96776b58cf4631911eecabdee7512e)`
of the registry dependency.
and it worked.

**Comment by Kylebrown9** [comment]
Since [`registry #102`](https://github.com/bytecodealliance/registry/pull/102) was merged, the API for accessing registry client storage has changed. Since `cargo-component` uses [git-based dependencies with no revision info](https://github.com/bytecodealliance/cargo-component/blob/main/Cargo.toml#L12) attempting to install `cargo-component` now pulls in an incompatible version of the registry code.

**Comment by peterhuene** [comment]
Also consider using the `--locked` option to ensure that the install follows `Cargo.lock` rather than using the latest dependencies.

We should update the README until such time that install works off solely off of published dependencies.
